language: python
services:
    - memcache
python:
    - 2.7
install:
    - "pip install -r reqs/ci.txt"
before_script:
    - psql -c 'create database xassr;' -U postgres
script:
    - export DJANGO_SETTINGS_MODULE="xassr.settings.ci"
    - export DATABASE_URL="postgres://localhost/xassr"
    - make test
